exclude_paths:
- ".meteor/*"
- "packages/meteor-react-router-ssr/*"
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 100
  eslint:
    enabled: true
  csslint:
    enabled: false
  markdownlint:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
ratings:
   paths:
   - "**.js"
   - "**.jsx"
   - "**.css"
