mongo:
  image: mongo:latest
  command: mongod --storageEngine=wiredTiger
nginx:
  image: ongoworks/nginx-proxy-ssl
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
  ports:
    - "80:80"
    - "443:443"
redoc:
  image: reactioncommerce/redoc:latest
  links:
    - mongo
    - nginx
  environment:
    ROOT_URL: "https://docs.reactioncommerce.com"
    MONGO_URL: "mongodb://mongo:27017/redoc"
    VIRTUAL_HOST: "docs.reactioncommerce.com"
