
redoc:
  image: reactioncommerce/redoc:latest
  ports:
    - 80:80
  links:
    - mongo
  restart: always
  environment:
    ROOT_URL: "http://example.com"
    MONGO_URL: "mongodb://mongo:27017/redoc"

mongo:
  image: mongo:latest
  restart: always
  command: mongod --storageEngine=wiredTiger
