# used for CircleCI curl tests

reaction:
  image: reactioncommerce/redoc:ci
  links:
    - mongo
  ports:
    - "80:80"
  environment:
    ROOT_URL: "http://localhost"
    MONGO_URL: "mongodb://mongo:27017/redoc"

mongo:
  image: mongo:latest
  command: mongod --storageEngine=wiredTiger
